### ISSUE TITLE
fails to build with aeson-0.8.0.2

### ISSUE THREAD

**Issue by juhp** [jgm/skylighting#28]
I think a lower bound is needed for aeson.
When I try to build with aeson-0.8.0.2 from Fedora 25, I get:

```
src/Skylighting/Types.hs:211:3:
    ‘toEncoding’ is not a (visible) method of class ‘ToJSON’
src/Skylighting/Types.hs:211:18: Not in scope: ‘toEncoding’
```

cf https://copr.fedorainfracloud.org/coprs/petersen/pandoc/build/684534/

**Comment by juhp** [comment]
It builds fine with aeson-1.0.2.1 in Fedora 26+.

**Comment by juhp** [comment]
Thanks
